sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 935184280abc

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJVSNSg2Zjm5BahWeG6
    access-key-secret: F8NJgFzu8LoTYSQPCvs8aHtwzi7rMU
    bucket-name: sky-itcast-zeratul
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxa6df4556625fc365
    secret: b640dee22c5d6f44d5e7ae7c55fe96f3
    notify-url: http://6e8e7527.r3.cpolar.cn/notify/paySuccess